server:
  port: 8080

spring:
  application:
    name: demo-app

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: info